### ISSUE TITLE
Q: What I need to set to host config parameter?

### ISSUE THREAD

**Issue by Flyr1Q** [PavelTkachenko/processing_kz#1]
First of all thank you for your gem.

Sorry if it is stupid question, but i didn't get what i need to set to :host config parameter. Processing provided me such a testing credentials (i've changed it a bit in case they are unique at some point)

MID - 000000000000112 (it is merchant_id i suppose)
WSDL - https://test.processing.kz/CNPMerchantWebServices/services/CNPMerchantWebService?wsdl
Test card - 4011 0010 3819 3535

So do i need to set host just http://www.processing.kz? Or do they have to provide something additional?

**Comment by Flyr1Q** [comment]
Ok, nevermind, just passed https://test.processing.kz/CNPMerchantWebServices/services/CNPMerchantWebService, everything is ok :+1:

**Comment by PavelTkachenko** [comment]
For production I use this config:
```ruby
  ProcessingKz.config do |config|
    config.wsdl = Rails.root + 'public/CNPMerchantWebService.wsdl'
    config.host = 'https://payment.processinggmbh.ch/CNPMerchantWebServices/services/CNPMerchantWebService'
    config.merchant_id = '0000000******90'
    config.language_code = 'ru'
    config.currency_code = 398
  end
```
As you can see, I put WSDL in public folder. Host is URL which was provided by processing.kz.
